// UNC Chapel Hill building coordinates + department metadata
// Coordinates sourced from UNC campus map (facilities.unc.edu)

export interface Building {
  id: string;
  name: string;
  shortName: string;
  lat: number;
  lng: number;
  subjects: string[]; // UNC subject codes taught here
  tag: string;
  yearBuilt?: number;
}

export const BUILDINGS: Building[] = [
  {
    id: "sitterson",
    name: "Sitterson Hall",
    shortName: "Sitterson",
    lat: 35.910178,
    lng: -79.053398,
    subjects: ["COMP"],
    tag: "Computer Science",
    yearBuilt: 1971,
  },
  {
    id: "phillips",
    name: "Phillips Hall",
    shortName: "Phillips",
    lat: 35.912502,
    lng: -79.050765,
    subjects: ["MATH", "STOR"],
    tag: "Mathematics & Statistics",
    yearBuilt: 1919,
  },
  {
    id: "gardner",
    name: "Gardner Hall",
    shortName: "Gardner",
    lat: 35.910723,
    lng: -79.050198,
    subjects: ["ECON", "POLI"],
    tag: "Economics & Political Science",
    yearBuilt: 1915,
  },
  {
    id: "hamilton",
    name: "Hamilton Hall",
    shortName: "Hamilton",
    lat: 35.912005,
    lng: -79.051822,
    subjects: ["ENGL", "CMPL"],
    tag: "English & Comparative Literature",
    yearBuilt: 1952,
  },
  {
    id: "davie",
    name: "Davie Hall",
    shortName: "Davie",
    lat: 35.909832,
    lng: -79.049215,
    subjects: ["PSYC"],
    tag: "Psychology",
    yearBuilt: 1964,
  },
  {
    id: "murphey",
    name: "Murphey Hall",
    shortName: "Murphey",
    lat: 35.911420,
    lng: -79.049850,
    subjects: ["HIST", "RELI"],
    tag: "History & Religious Studies",
    yearBuilt: 1923,
  },
  {
    id: "carroll",
    name: "Carroll Hall",
    shortName: "Carroll",
    lat: 35.909300,
    lng: -79.048200,
    subjects: ["MEJO"],
    tag: "Media & Journalism",
    yearBuilt: 1957,
  },
  {
    id: "genome",
    name: "Genome Sciences Building",
    shortName: "Genome Sci",
    lat: 35.906534,
    lng: -79.055640,
    subjects: ["BIOL", "GNET"],
    tag: "Biology & Genetics",
    yearBuilt: 2008,
  },
  {
    id: "caudill",
    name: "Caudill Labs",
    shortName: "Caudill",
    lat: 35.910900,
    lng: -79.054200,
    subjects: ["CHEM", "BCHE"],
    tag: "Chemistry & Biochemistry",
    yearBuilt: 1968,
  },
  {
    id: "mitchell",
    name: "Mitchell Hall",
    shortName: "Mitchell",
    lat: 35.912800,
    lng: -79.049100,
    subjects: ["SOCI", "ANTH"],
    tag: "Sociology & Anthropology",
    yearBuilt: 1922,
  },
  {
    id: "kenan",
    name: "Kenan-Flagler Business School",
    shortName: "Kenan-Flagler",
    lat: 35.904410,
    lng: -79.051940,
    subjects: ["BUSI", "IBUS"],
    tag: "Business",
    yearBuilt: 1997,
  },
  {
    id: "hanes",
    name: "Hanes Art Center",
    shortName: "Hanes Art",
    lat: 35.910600,
    lng: -79.047500,
    subjects: ["ARTH", "ARTV"],
    tag: "Art History & Studio Art",
    yearBuilt: 1984,
  },
  {
    id: "graham",
    name: "Graham Memorial",
    shortName: "Graham",
    lat: 35.912100,
    lng: -79.047800,
    subjects: ["COMM"],
    tag: "Communication Studies",
    yearBuilt: 1931,
  },
  {
    id: "greenlaw",
    name: "Greenlaw Hall",
    shortName: "Greenlaw",
    lat: 35.912700,
    lng: -79.050500,
    subjects: ["LING", "FREN", "SPAN"],
    tag: "Languages & Linguistics",
    yearBuilt: 1968,
  },
  {
    id: "wilson",
    name: "Wilson Library",
    shortName: "Wilson",
    lat: 35.911500,
    lng: -79.052900,
    subjects: ["INLS"],
    tag: "Information & Library Science",
    yearBuilt: 1929,
  },
];
